### PR TITLE
added Piwik support in analytics.html #127

### PR DESCRIPTION
**Pull request by clue404**

### CODE REVIEW

**Comment by iranzo** [comment]
Why was this closed? Was on a merge?

**Comment by iranzo** [comment]
@clue404 would you mind revisiting this in case the code block needs to be updated?

Thanks

@silverhook can you assign this to me too?

**Comment by clue404** [comment]
Wow I totally forgot about this. I don't have the repo so I can't reopen

**Comment by iranzo** [comment]
I think we can commit this as the if code looks sane or we can test setting up a piwik url, test and then merge from the actual code base as there are no code conflicts with actual 'master'

Thoughts?

**Comment by silverhook** [comment]
At a quick glance I don’t see how this could conflict with master – it’s a pretty much independent if block.

As @clue404 can’t re-open (due to missing repo), we should open a new PR with the same content and credit @clue404 for providing the solution in the `THANKS` file.

**Comment by iranzo** [comment]
I do think that we can reopen this and directly merge, as even if clue404 closed the repo, still the merge is here, if you reopen you could be able to merge the request.

**Comment by iranzo** [comment]
I do think that we can reopen this and directly merge, as even if clue404 closed the repo, still the merge is here, if you reopen you could be able to merge the request.

**Comment by silverhook** [comment]
I can’t reopen it – GitHub won’t let me because the repo that the PR originates from was deleted.

**Comment by iranzo** [comment]
Ok, I'll get diff, git-blame-someone-else to cool404 and commit PR

**Comment by silverhook** [comment]
Perfect.

**Comment by talha131** [comment]
@iranzo you may already know this, just wanted to point out you can get patch and diff from following links. You can apply patch using `git apply`, without having to edit the files.

1. Patch: https://patch-diff.githubusercontent.com/raw/Pelican-Elegant/elegant/pull/160.patch
1. Diff: https://patch-diff.githubusercontent.com/raw/Pelican-Elegant/elegant/pull/160.diff

**Comment by iranzo** [comment]
Yes, but the idea was to also in git log, leave author as comiter (via git-blame-someone-else) 

I'll do that

**Pull request closed without merging**
